# Generated by Django 5.2 on 2025-10-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='target',
            field=models.CharField(choices=[('SUMMARIZE', 'SUMMARIZE'), ('SYSTEM', 'SYSTEM')], max_length=20),
        ),
    ]
